// <auto-generated />
using Frutas.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Frutas.Core.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    partial class DataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Frutas.Core.Models.FruitModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Valor_A")
                        .HasColumnType("int");

                    b.Property<int>("Valor_B")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Frutas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Banana",
                            Valor_A = 10,
                            Valor_B = 20
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Maça",
                            Valor_A = 30,
                            Valor_B = 10
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Melancia",
                            Valor_A = 20,
                            Valor_B = 5
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Mamão",
                            Valor_A = 11,
                            Valor_B = 7
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
